### ISSUE TITLE
Refactor curriculum metrics - to take a course as input, rather than a vertex index

### ISSUE THREAD

**Issue by heileman** [CurricularAnalytics/CurricularAnalytics.jl#15]

**Comment by haydenfree** [comment]
@heileman I think this refactor may have already been completed. I quickly searched and didn't spot anywhere that you're required to pass a vertex ID. In the documentation `requisite_distance` is listed to require an arg course of type `Int`, but the function code actually expects a type `Course`. I've attached an image showing this.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/1368490/68800175-94504080-0627-11ea-90f1-6355a6117369.png">
