### ISSUE TITLE
Make plan and curriculum visualization apps.

### ISSUE THREAD

**Issue by kevinwarne** [CurricularAnalytics/CurricularAnalytics.jl#22]
here are the vue curricula analytics docs. I would probably make separate embed_client_plan and embed_client_curriculum vue applications that use the plugin with different configurations. Take a look at `embed_client/src/views/Graph.vue` to see where most of the plugin abstraction code is.

[vue-curricula-docs.pdf](https://github.com/heileman/CurricularAnalytics.jl/files/2605307/vue-curricula-docs.pdf)

**Comment by orhanabar** [comment]
When I run 
`yarn install`
I am getting this error:
```
yarn install v1.12.3
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@unm-idi%2fvue-curricula: Not found".
info If you think this is a bug, please open a bug report with the information provided in "...\\embed_client\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Do you know why I am getting this error?
