### ISSUE TITLE
Fix Longest Path in Visualization

### ISSUE THREAD

**Issue by haydenfree** [CurricularAnalytics/CurricularAnalytics.jl#29]
The visualization currently generates the longest path itself. It should instead accept the longest path from the toolbox and visualize it that way.

**Comment by haydenfree** [comment]
@heileman There is a longest_paths() function defined in CurricularAnalytics.jl that takes a `Curriculum` as input. It is used in the basic_metrics calculation.

There is a longest_paths() and a longest_path() function defined in GraphAlgs.jl that take an AbstractGraph as input. These two functions are not exported (cannot be called outside of the toolbox), and I do not see them used anywhere in the source code.

Could you double check these and see if they're redundant / can be removed?

I've attached images for clarity.

**Version defined in CurricularAnalytics.jl**
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1368490/68800960-112fea00-0629-11ea-8f74-8f8e2d50ac6f.png">

**Versions defined in GraphAlgs.jl**
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1368490/68801014-2d338b80-0629-11ea-882f-12f133e090d2.png">

**Comment by heileman** [comment]
Hayden,

I’m on this — thanks for catching the issue where the index changed to an actual course object.  We do need multiple functions though.  I will explain in a more detailed email later today.

Thanks, 
 -Greg

**Comment by haydenfree** [comment]
^The above functions are all needed and don't need to be removed or changed
