### ISSUE TITLE
Error in Calculated Delay Factor

### ISSUE THREAD

**Issue by benhawk1** [CurricularAnalytics/CurricularAnalytics.jl#85]
When creating degree plans, I noticed that several of the courses in the plan were displaying delay factors that appeared to be incorrect. Included in attachments are screenshots of the erroneous delay factors, as well as a word document containing code that can be used to replicate the display for errors 1 through 3.

Currently using CurricularAnalytics v0.6.6 and Julia v1.2.0, though this error was also occurring on CurricularAnalytics v0.6.3.

(Notes: Correct value for photo 1's delay factor is 7 (displayed as 4), photo 2's factor should be 7 (displayed as 5), photo 3 should be 8 (displayed as 6), photo 4 should be 6 (displayed as 5))

Please let me know if you need any more information regarding the bug, and thank you for your help!

![Erroneous Delay Factor 1](https://user-images.githubusercontent.com/60792806/74186470-b2bedb80-4c18-11ea-98e2-645d61e550ac.png)
![Erroneous Delay Factor 2](https://user-images.githubusercontent.com/60792806/74186480-b5213580-4c18-11ea-864a-f768e2ef0343.png)
![Erroneous Delay Factor 3](https://user-images.githubusercontent.com/60792806/74186484-b7838f80-4c18-11ea-80b6-91b120b79c8b.png)
![Erroneous Delay Factor 4](https://user-images.githubusercontent.com/60792806/74186488-b94d5300-4c18-11ea-8451-47074aedadc6.png)

[ENME Curricular Analytics Code.docx](https://github.com/CurricularAnalytics/CurricularAnalytics.jl/files/4182862/ENME.Curricular.Analytics.Code.docx)

**Comment by haydenfree** [comment]
Ben,

Thanks so much for bringing this bug to our attention. There should be tests built in that check the metrics are being calculated correctly, but clearly at the least the visualization isn't showing the correct numbers. We will work to correct this as soon as possible.

**Comment by heileman** [comment]
Ben, can you send me the CSV files you used to create these programs? (greg.heileman@gmail.com)
Thanks for reporting the bug.
 -Greg

**Comment by benhawk1** [comment]
Sure thing! I'll send them now.

**Comment by heileman** [comment]
Fixed: delay_factor() was not finding all long paths, now it does.
![Screen Shot 2020-02-13 at 12 52 29 PM](https://user-images.githubusercontent.com/250999/74473141-577f2a00-4e60-11ea-91f6-1560bd5e2429.png)
![Screen Shot 2020-02-13 at 12 53 08 PM](https://user-images.githubusercontent.com/250999/74473146-5817c080-4e60-11ea-98ad-16eaf3a657bd.png)
![Screen Shot 2020-02-13 at 12 53 43 PM](https://user-images.githubusercontent.com/250999/74473147-5817c080-4e60-11ea-9826-fc6661841c8b.png)
![Screen Shot 2020-02-13 at 12 50 31 PM](https://user-images.githubusercontent.com/250999/74473156-59e18400-4e60-11ea-90e3-86ba8f167b3e.png)
